void fun(int n, float a[n], int m, float b[m]) {
  float sum = 0.0;
  for(int i=0; i<n; i++) {
    sum += a[i];
  }
  for(int i=0; i<m; i++) {
    b[i] = sum;
  }
}

/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 17 Dec 2020 10:03
*/
/*
  Differentiation of fun in forward (tangent) mode:
   variations   of useful results: b[0:m-1]
   with respect to varying inputs: a[0:n-1]
   RW status of diff variables: a:(loc) a[0:n-1]:in b:(loc) b[0:m-1]:out
   Plus diff mem management of: a:in b:in
*/
void fun_d(int n, float a[n], float ad[n], int m, float b[m], float bd[m]) {
    float sum = 0.0;
    float sumd;
    sumd = 0.0;
    {
      int ii1;
      for (int i = 0; i < n; ++i) {
          sumd = sumd + ad[i];
          sum += a[i];
      }
      for (ii1 = 0; ii1 < m; ++ii1)
          bd[ii1] = 0.0;
    }
    for (int i = 0; i < m; ++i) {
        bd[i] = sumd;
        b[i] = sum;
    }
}

/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 17 Dec 2020 10:03
*/
//#include <adBuffer.h>
// We do not need to include this. If there are calls to PUSH** or POP** in
// your code, download the ADFirstAidKit containing the AD stack library from
// the Tapenade website.

/*
  Differentiation of fun in reverse (adjoint) mode:
   gradient     of useful results: b[0:m-1]
   with respect to varying inputs: a[0:n-1] b[0:m-1]
   RW status of diff variables: a:(loc) a[0:n-1]:out b:(loc) b[0:m-1]:in-out
   Plus diff mem management of: a:in b:in
*/
void fun_b(int n, float a[n], float ab[n], int m, float b[m], float bb[m]) {
    float sum = 0.0;
    float sumb = 0.0;
    sumb = 0.0;
    for (int i = m-1; i > -1; --i) {
        sumb = sumb + bb[i];
        bb[i] = 0.0;
    }
    {
      int ii1;
      for (ii1 = 0; ii1 < n; ++ii1)
          ab[ii1] = 0.0;
      for (int i = n-1; i > -1; --i)
          ab[i] = ab[i] + sumb;
    }
}
